name: bashtest

on: [push]

jobs:
  bashtest:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'no-workflow')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run bash tests
        env:
          ULTRALYTICS_API_KEY: ${{ secrets.ULTRALYTICS_API_KEY }}
          WEBDAV_HOSTNAME: ${{ secrets.WEBDAV_HOSTNAME }}
          WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          echo "ULTRALYTICS_API_KEY: $ULTRALYTICS_API_KEY"
          echo "WEBDAV_HOSTNAME: $WEBDAV_HOSTNAME"
          echo "WEBDAV_LOGIN: $WEBDAV_LOGIN"
          echo "WEBDAV_PASSWORD: $WEBDAV_PASSWORD"

          ./.github/workflows/bashtest.sh vancouver_watching
